#!/bin/bash

# git post-commit hook to snap an image of your smiling face.
set -e

# running from gitx does not set path properly
export PATH="$PATH:/usr/local/bin/"

# if we are on a branch (and not in the middle of a rebase)
if git symbolic-ref -q --short HEAD 2>&1 > /dev/null ; then
  PHOTO_NAME="${HOME}/Pictures/git/$(date '+%Y_%m_%d-%H_%M_%S').jpg"
  [ -t 1 ] && echo "Say Cheese"
  # wait 2 seconds to let the camera aperture adjust to room light
  imagesnap -q -w 2.5 ${PHOTO_NAME}
fi
