#!/bin/sh
#
# * Put this in manageiq/.git/hooks/post-checkout
# * Make sure you chmod +x this file!!!
# * Make you convert this file to unix line endings, NOT dos/windows.
# * 5.3.z needs ruby 1.9.3 with bundler ~1.3.5.
# * Master needs ruby 2+ with bundler ~1.5+.
# * You have to `bundle` once on 5.3.z to populate the empty Gemfile.lock.5.3.z
# * If you have a long running branch such as rails4 and want a Gemfile.lock
#    just for this branch:
#    `touch Gemfile.lock.rails4`, `git checkout rails4`, `bundle`.
## * If you are based upon another branch:
##     "git config --add branch.${branch}.gemfile Gemfile.lock.${branch}"

branch=$(git symbolic-ref -q --short HEAD)
root_dir=$(git rev-parse --show-toplevel)
ver_dir="${root_dir}/.ver"

# dropped configuration for branch specific gemfiles
# git_lockfile=$(git config --get branch.$branch.gemfile)

branch_lockfile="${ver_dir}/Gemfile.lock.${branch}"
if [ -f ${branch_lockfile} ] ; then
  lockfile="${branch_lockfile}"
else
  ret=$(git diff upstream/master -- Gemfile)

  if [[ $( echo "${ret}" | wc -c) -gt 1 ]] ; then
    echo "    Gemfile differs from upstream/master, may want to run a custom gem lockfile via:"
    echo "       git gemfile"
    echo ">> ${ret}"
  fi

  lockfile="${ver_dir}/Gemfile.lock.master"
fi

if [ -f "$lockfile" ] ; then
  rm -f ${root_dir}/Gemfile.lock
  ln -s $lockfile ${root_dir}/Gemfile.lock
fi

# TODO: may want to get v2key or GUID back
